### ISSUE TITLE
EventInterface should return instances of DateTime

### ISSUE THREAD

**Issue by shadowhand** [benplummer/calendarful#2]
Currently `getStartDate` and `getEndDate` have a return type of `mixed`, which is totally unnecessary. If an event is supposed to represent an absolute moment in time, the start and end values must be exact and can therefore be represented as `DateTime` objects.

This also simplifies logic later, such as in `Calendar::removeOutOfRangeEvents` because you can compare without formatting:

```php
// existing code
if ($event->getStartDate() <= $toDate->format('Y-m-d H:i:s') && $event->getEndDate() >= $fromDate->format('Y-m-d H:i:s')) { ... }

// becomes
if ($event->getStartDate() <= $toDate && $event->getEndDate() >= $fromDate) { ... }
```

**Comment by shadowhand** [comment]
This also affects [other code too](https://github.com/benplummer/calendarful/blob/4394e23c224f93db9cf245f3f96050775f8c5490/src/Recurrence/Type/Daily.php#L67-L69) where lots of conversion to/from DateTime objects is done.

**Comment by shadowhand** [comment]
After looking through more of the code, I really think this is **the** top concern I have with this library right now... I see far too many instances where dates are being passed around and manipulated as strings, which is simply not a realistic representation of dates.

The only accurate way to represent a moment in time is with an epoch offset (UNIX timestamp being the most common in PHP) because a string becomes instantly incorrect as soon as timezone is changed. Even storing a date as a complete ISO string with a timezone can never be accurate because it won't account for leap seconds or modifications to timezone rules, which happen several times a year in various countries.

There are (possibly significant) performance benefits to using DateTime objects throughout the application, as you will save much effort in converting from string to epoch and back again.

**Comment by trowski** [comment]
I strongly agree with @shadowhand. Using strings to pass dates around will lead to bugs.

I forked the library and started trying to alter the library to use `\DateTime` objects in `EventInterface`, but I ran into trouble when `MockEvent` kept returning a non-object from `getStartDate()`, even though I modified the method to return the object that I created in the constructor. Is Mockery doing something with that I don't understand?

`\DateTime` objects also shouldn't be created without specifying a timezone with a `\DateTimeZone` object, otherwise you're relying on `date.timezone` being set in `php.ini`, and it might not be set to what the user intended. If everything were modified to only accept `\DateTime` objects instead of strings, you could avoid this issue since the user would have to worry about constructing the `\DateTime` objects.

**Comment by benplummer** [comment]
All dates throughout the package are now stored and passed as \DateTime objects rather than date formatted strings. Thanks for the input guys!
